### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#15]
Hi,

did a fresh install.

Now:
```
$ mobie.add_image_data --input_path aligned_full_stomach/ --input_key *.tif --root `pwd`/aligned_full_stomach --dataset_name mobie2 --image_naem 3view --resolution [15,15,50] --scale_factors [[1, 2, 2], [2, 2, 2], [2, 2, 2]] --chunks [64,128,128,128] --target slurm --max_jobs 80  
Traceback (most recent call last):
  File "/g/emcf/software/python/miniconda/envs/mobie/bin/mobie.add_image_data", line 33, in <module>
    sys.exit(load_entry_point('mobie', 'console_scripts', 'mobie.add_image_data')())
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/__init__.py", line 1, in <module>
    from .image_data import add_image_data
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/image_data.py", line 6, in <module>
    from mobie.import_data import import_raw_volume
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/import_data/__init__.py", line 5, in <module>
    from .traces import import_traces
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/import_data/traces.py", line 5, in <module>
    import elf.skeleton.io as skio
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/elf/skeleton/__init__.py", line 1, in <module>
    from .skeletonize import skeletonize, get_method_names
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/elf/skeleton/skeletonize.py", line 1, in <module>
    from .thinning import thinning
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/elf/skeleton/thinning.py", line 3, in <module>
    from skan import csr
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/skan/__init__.py", line 1, in <module>
    from .csr import skeleton_to_csgraph, branch_statistics, summarize, Skeleton
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.7/site-packages/skan/csr.py", line 21, in <module>
    @numba.jitclass(csr_spec)
AttributeError: module 'numba' has no attribute 'jitclass'
```

**Comment by constantinpape** [comment]
Looks like the dependency for numba has to be pinned because `numba.jitclass` was moved to `numba.experimental.jitclass`.
I have updated the environment file accordingly.
You can try to downgrade numba in the env you have or pull and reinstall the environment.

For downgrading numba, you need to go to a version smaller than 0.52.
Something like `conda install -c conda-forge numba=0.51.2` should work (haven't tested it),

**Comment by martinschorb** [comment]
That did it...
