### ISSUE TITLE
mobie.add_image fails

### ISSUE THREAD

**Issue by jhennies** [mobie/mobie-utils-python#25]
Running mobie-utils from #21

Running this code snippet:

```
import mobie

root = '/data/tmp/mobie_no_table_test/data/'
dataset_name = 'test_ds'

mobie.add_image(
    input_path='/data/datasets/platy_data.n5',
    input_key='/setup0/timepoint0/s1',
    root=root,
    dataset_name=dataset_name,
    image_name='em-raw',
    resolution=[0.02, 0.02, 0.02],
    chunks=[64, 64, 64],
    scale_factors=2*[[2, 2, 2]],
    is_default_dataset=True,
    target='local',
    max_jobs=12,
    unit='micrometer'
)
```

errors out with

```
Traceback (most recent call last):
  File "/home/hennies/.config/JetBrains/PyCharmCE2021.1/scratches/scratch_9.py", line 21, in <module>
    unit='micrometer'
  File "/home/hennies/src/github/mobie/mobie-utils-python/mobie/image_data.py", line 61, in add_image
    metadata.add_source_metadata(dataset_folder, 'image', image_name, image_metadata_path, view=view)
  File "/home/hennies/src/github/mobie/mobie-utils-python/mobie/metadata/source_metadata.py", line 93, in add_source_metadata
    validate_source_metadata(source_name, source_metadata, dataset_folder)
  File "/home/hennies/src/github/mobie/mobie-utils-python/mobie/validation/metadata.py", line 73, in validate_source_metadata
    assert_equal(name, bdv_name)
  File "/home/hennies/src/github/mobie/mobie-utils-python/mobie/validation/utils.py", line 59, in _assert_equal
    raise ValueError(msg)
ValueError
```

As far as I understand, the name field is created incorrectly in the em-raw.xml (see below) - the failing assertion requires it to be 'em-raw':

```
<SpimData version="0.2">
  <BasePath type="relative">.</BasePath>
  <SequenceDescription>
    ...
    <ViewSetups>
      ...
      <ViewSetup>
        <id>0</id>
        <name>Setup0</name>
        ...
      </ViewSetup>
    </ViewSetups>
    ...
  </SequenceDescription>
  ...
</SpimData>
```

**Comment by constantinpape** [comment]
This works for me, I assume the issue is in some outdated upstream packages. Could you please make sure to use the current master of
- [elf](https://github.com/constantinpape/elf)
- [cluster_tools](https://github.com/constantinpape/cluster_tools)
- [pybdv](https://github.com/constantinpape/pybdv)

These are all pure python, so installation should be easy.
(I will draft new releases soon.)
