### ISSUE TITLE
handling views

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-utils-python#27]
Hi,

I found `get_views` to be my entry point in writing new views into a dataset.

How does this handle crops?
Do I need to provide the JSON as a dictionary "view" for now and feed it through [`add_view_to_dataset`](https://github.com/mobie/mobie-utils-python/blob/171012c6ff2959289851e2bf00eca0d1edea2a5f/mobie/metadata/dataset_metadata.py#L54)?

**Comment by martinschorb** [comment]
OK, I think I understand now. I provide the trafo/crop dict as `SourceTransforms` in `get_views`. I guess I can then feed this into [`add_view_to_dataset`](https://github.com/mobie/mobie-utils-python/blob/171012c6ff2959289851e2bf00eca0d1edea2a5f/mobie/metadata/dataset_metadata.py#L54)

**Comment by constantinpape** [comment]
> I provide the trafo/crop dict as `SourceTransforms` in `get_views`. I guess I can then feed this into [`add_view_to_dataset`](https://github.com/mobie/mobie-utils-python/blob/171012c6ff2959289851e2bf00eca0d1edea2a5f/mobie/metadata/dataset_metadata.py#L54)

Exactly! I will try to add some more examples / documentation for this soon.

**Comment by martinschorb** [comment]
And I could not find a function similar to `get_views` for adding sources.
Do I need to provide that dict manually?

**Comment by martinschorb** [comment]
or does something like `add_source_to dataset` exist?

**Comment by martinschorb** [comment]
I would like to incrementally add the sources as I go through the analysis. I only found a way to add them using `create_dataset_metadata` and writing everything at once. Is this the only way atm?

**Comment by martinschorb** [comment]
- https://github.com/mobie/mobie-utils-python/blob/171012c6ff2959289851e2bf00eca0d1edea2a5f/mobie/metadata/source_metadata.py#L76 needs to be updated to `image_metadata_path`.

- I am in the MoBIE project dir and call:
   ```Python
        mm.add_source_metadata(dataset_folder = './data/tomo/',
                               source_type = 'image',
                               source_name = sourcename,
                               image_metadata_path = newxml
                               )
```

and get  an error when validating the dataset directory.

```

  File ".../mobie-utils-python/mobie/metadata/source_metadata.py", line 102, in add_source_metadata
    validate_source_metadata(source_name, source_metadata, dataset_folder)

  File ".../mobie-utils-python/mobie/validation/metadata.py", line 75, in validate_source_metadata
    assert_equal(name, bdv_name)

  File ".../mobie-utils-python/mobie/validation/utils.py", line 59, in _assert_equal
    raise ValueError(msg)

ValueError
```
What could cause this?

**Comment by constantinpape** [comment]
The name of the source and the name in the xml do not agree.

**Comment by martinschorb** [comment]
Ah, makes sense. it replaces not only the link to the n5 but also the source name.

**Comment by martinschorb** [comment]
runs now!

**Comment by martinschorb** [comment]
But the [`dataset.json`](https://github.com/mobie/MM_centrioles-tomo-datasets/blob/63e758f9f381d3189d419b4e2c321cb2e682e361/data/tomo/dataset.json) that I created this way crashes MoBIE :-(

```
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.mobie.MoBIE.setImageDataFormat(MoBIE.java:110)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:86)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:26)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
I changed ` "uiSelectionGroup"` to  `"bookmark"` to make sure it exists. This does not solve it...

**Comment by martinschorb** [comment]
OK, it seems to be a problem with the XML

**Comment by martinschorb** [comment]
```
 java.nio.file.NoSuchFileException: /Volumes/schwab/Tobias/MoBIE/data/tomo/images/bdv-n5/./PCL/PCL_0000_Grid2_PCL_0000_Grid2_c0091.n5/setup0/attributes.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.<init>(N5FSReader.java:69)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.openForReading(N5FSReader.java:58)
	at org.janelia.saalfeldlab.n5.N5FSReader.getAttributes(N5FSReader.java:161)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.getAttribute(AbstractGsonReader.java:128)
	at bdv.img.n5.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:196)
	at bdv.img.n5.N5ImageLoader.open(N5ImageLoader.java:145)
	... 16 more
```

The folder and file exist. 
Is it the extra `/./` in the path that kills it?

**Comment by martinschorb** [comment]
OK, my fault... Double Patient ID

**Comment by martinschorb** [comment]
BDV now likes the XML, but MoBIE still throws the same error.

The [JSON](https://github.com/mobie/MM_centrioles-tomo-datasets/blob/25226af7fbfb051fe25730a50cd7f2dd67e3b7ce/data/tomo/dataset.json) looks good to me as well.

Any ideas?

**Comment by constantinpape** [comment]
Can you try to update MoBIE-beta again?

**Comment by martinschorb** [comment]
just did. Same behaviour.

**Comment by constantinpape** [comment]
The "project.json" file is not quite up-to-date.
It needs a "imageDataFormats", see https://github.com/mobie/platybrowser-datasets/blob/spec-v2/data/project.json#L28-L31.
In your case this would only be `["bdv.n5"]`.

**Comment by martinschorb** [comment]
OK, we are making progress.

Now it crashes when loading the image data:

```
IRunTimeClassAdapters : 
	 interface bdv.viewer.render.AccumulateProjectorFactory
	 	 class de.embl.cba.mobie.bdv.render.AccumulateOccludingProjectorARGBFactory
	 	 class sc.fiji.bdvpg.bdv.projector.DefaultAccumulatorFactory
	 interface sc.fiji.bdvpg.bdv.supplier.IBdvSupplier
	 	 class de.embl.cba.mobie.bdv.MobieBdvSupplier
	 	 class sc.fiji.bdvpg.bdv.supplier.DefaultBdvSupplier
	 interface net.imglib2.realtransform.RealTransform
	 	 class net.imglib2.realtransform.AffineTransform3D
	 	 class net.imglib2.realtransform.InvertibleRealTransformSequence
	 	 class net.imglib2.realtransform.RealTransformSequence
	 	 class net.imglib2.realtransform.ThinplateSplineTransform
	 	 class net.imglib2.realtransform.Wrapped2DTransformAs3D
	 	 class net.imglib2.realtransform.inverse.WrappedIterativeInvertibleRealTransform
IClassAdapters : 
	 class net.imglib2.realtransform.AffineTransform3D
	 class net.imglib2.realtransform.InvertibleRealTransformSequence
	 class net.imglib2.realtransform.RealTransformSequence
	 class net.imglib2.realtransform.ThinplateSplineTransform
	 class net.imglib2.realtransform.Wrapped2DTransformAs3D
	 class net.imglib2.realtransform.inverse.WrappedIterativeInvertibleRealTransform
[WARN] Overriding action Change random coloring seed [ Ctrl L ]
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:218)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:151)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:87)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:26)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
it seems it is missing the default image/view to show when loading.

**Comment by constantinpape** [comment]
> it seems it is missing the default image/view to show when loading.

For this you will need to add a view called `default` with `uiSelectionGroup: bookmark`.

**Comment by martinschorb** [comment]
So, I need to do one `get_default_view`and then add this view with `add_view_to_dataset`.

**Comment by martinschorb** [comment]
YEAH!

**Comment by martinschorb** [comment]
I now do:

```Python
        # generate tomo view
        disp = mm.view_metadata.get_image_display(sourcename,[sourcename])

        view = mm.get_view([sourcename], ['image'], [[sourcename]], [disp], True, sourcename)
```
To generate the view of the entire tomo.

I get:
```
    view = mm.get_view([sourcename], ['image'], [[sourcename]], [disp], True, sourcename)

  File ".../mobie-utils-python/mobie/metadata/view_metadata.py", line 142, in get_view
    display = get_image_display(name, source_list, **display_setting)

  File ".../mobie-utils-python/mobie/metadata/view_metadata.py", line 22, in get_image_display
    raise ValueError(f"Invalid keyword arguments for image display: {list(kwargs.keys())}")

ValueError: Invalid keyword arguments for image display: ['imageDisplay']
```

but this dict was just generated before...?

**Comment by constantinpape** [comment]
> ```python
>         # generate tomo view
>         disp = mm.view_metadata.get_image_display(sourcename,[sourcename])
> 
>         view = mm.get_view(names = [sourcename],
>                            source_types = ['image'],
>                            sources = [[sourcename]],
>                            display_settings = [disp],
>                            is_exclusive = True,
>                            menu_name = sourcename,
>                            source_annotation_displays='Tomograms')
> ```

I see. There is some inconsistency in the API here. For now, can you try
```
view = mm.get_view(...
  disply_settings=[disp["imageDisplay"]])
```
instead? I am still not sure if this will fix everything, you might need to extract some more field names.

Note that what you are doing should work and I will fix it, but don't have time to work on it before Monday.

**Comment by martinschorb** [comment]
Did not fix it, I will try manually for now...

**Comment by martinschorb** [comment]
```Python
d2=disp["imageDisplay"]
d2.pop('name')
d2.pop('sources')
disp=d2
```
was the workaround

**Comment by martinschorb** [comment]
one more weird thing happens validating the transform...

```Python

```trafo
Out[128]: 
array([ 0.49597521,  0.72006439,  0.48529977,  0.        , -0.72006439,
        0.65340821, -0.23359149,  0.        , -0.48529977, -0.23359149,
        0.842567  ,  0.        ])

            affine_trafo = mm.get_affine_source_transform([sourcename],trafo)

            cview = mm.get_view(names = [centname],
                    source_types = ['image'],
                    sources = [[sourcename]],
                    display_settings = [disp],
                    is_exclusive = True,
                    menu_name = 'Centrioles',
                    source_transforms = [affine_trafo                                         
                                         ])

            mm.add_view_to_dataset(dataset_folder = datadir,                                       
                                   view_name = centname + "_crop",
                                   view = cview)
```

results in:

```

  File ".../mobie-utils-python/mobie/metadata/dataset_metadata.py", line 55, in add_view_to_dataset
    validate_view_metadata(view)

  File ".../mobie-utils-python/mobie/validation/metadata.py", line 110, in validate_view_metadata
    assert_true(False, msg)

  File ".../mobie-utils-python/mobie/validation/utils.py", line 64, in _assert_true
    raise ValueError(msg)

ValueError: array([ 0.49597521,  0.72006439,  0.48529977,  0.        , -0.72006439,
        0.65340821, -0.23359149,  0.        , -0.48529977, -0.23359149,
        0.842567  ,  0.        ]) is not of type 'array'

Failed validating 'type' in schema[0]['properties']['affine']['properties']['parameters']:
    {'description': 'Parameters of the affine transformation, using the '
                    'BigDataViewer convention.',
     'items': {'type': 'number'},
     'maxItems': 12,
     'minItems': 12,
     'type': 'array'}

On instance['affine']['parameters']:
    array([ 0.49597521,  0.72006439,  0.48529977,  0.        , -0.72006439,
            0.65340821, -0.23359149,  0.        , -0.48529977, -0.23359149,
            0.842567  ,  0.        ])
```

**Comment by constantinpape** [comment]
> one more weird thing happens validating the transform...

It needs to be a plain python list, not a numpy array! If you do `affine_trafo.tolist()` that should fix it.

**Comment by martinschorb** [comment]
OK, cool. Probably it would make sense to include that conversion in `get_affine_source_transform` as well.

**Comment by martinschorb** [comment]
i was just confused by the message "array ... is not of type array."

**Comment by constantinpape** [comment]
> Probably it would make sense to include that conversion in `get_affine_source_transform` as well.

Yes! I will also fix this on Monday.
(And overall it's great that you test these things here so I can improve the lower level API).

> i was just confused by the message "array ... is not of type array."

Yes, that's because the equivalent of python lists are called arrays in javascript (amnd hence also in json)

**Comment by martinschorb** [comment]
:-(

it even prevents some manual hacks... But we are really getting close.
```

  File ".../mobie-utils-python/mobie/validation/utils.py", line 54, in validate_with_schema
    jsonschema.validate(instance=metadata, schema=schema)

  File ".../jsonschema/validators.py", line 934, in validate
    raise error
ValueError: Additional properties are not allowed ('sourceNamesAfterTransform' was unexpected)
```

**Comment by constantinpape** [comment]
That should actually work, but you may need to clear your cache:
`rm ~/.mobie/*.json`

**Comment by constantinpape** [comment]
`sourceNamesAfterTransform` is in the jsonschema already, e.g. https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L442

**Comment by martinschorb** [comment]
Still doesn't like it...
I am up-to-date with spec-v2.

**Comment by constantinpape** [comment]
I think then you're putting the `sourceNamesAfterTransform` into a wrong space, can you print the dict here?

**Comment by martinschorb** [comment]
that's the view:

```JSON
{'isExclusive': True,
 'uiSelectionGroup': 'Centrioles',
 'sourceDisplays': [{'imageDisplay': {'color': 'white',
    'contrastLimits': [0.0, 255.0],
    'name': 'PCL_00_Grid2_c0091_c1',
    'opacity': 1.0,
    'sources': ['PCL_00_Grid2_c0091']}}],
 'sourceTransforms': [{'affine': {'sources': ['PCL_00_Grid2_c0091'],
    'parameters': [0.49597520764843483,
     0.7200643938182488,
     0.48529976525159124,
     0.0,
     -0.720064393818249,
     0.6534082058352588,
     -0.23359149235857407,
     0.0,
     -0.4852997652515914,
     -0.2335914923585741,
     0.8425670018131762,
     0.0]},
   'sourceNamesAfterTransform': 'PCL_00_Grid2_c0091_c1_tfm'}]}
```

**Comment by constantinpape** [comment]
`sourceNamesAfterTransform` needs to go into `affine`.

**Comment by martinschorb** [comment]
makes sense...

**Comment by martinschorb** [comment]
and it needs to be a list.

Now it works !

**Comment by martinschorb** [comment]
- have a `get_crop` or similar for crops

**Comment by constantinpape** [comment]
@martinschorb I implemented all chages; can you remove your workarounds and check if all of this works for you now?

**Comment by martinschorb** [comment]
Almost everything seems to run.

I have a validation error

```
    cview = mm.get_view(names = [centname],
                    source_types = ['image'],
                    sources = [[sourcename]],
                    display_settings = [disp],
                    is_exclusive = True,
                    menu_name = 'Centrioles',
                    source_transforms = [affine_trafo,                                         
                                         crop])


  File ".../mobie-utils-python/mobie/metadata/view_metadata.py", line 252, in get_view
    raise ValueError(msg)

ValueError: Invalid sources in transform: ['B-CLL_00_Grid3_c0016_c1_tfm']

```

Is this the crop?

```Python
            crop = mm.get_crop_source_transform(sources = [centname + '_tfm'],
                                                min = cropmin,
                                                max = cropmax,                                                                                               
                                                source_names_after_transform = [
                                                    centname + "_crop"
                                                    ]
                                                )
```

**Comment by martinschorb** [comment]
Yes,
when I do 

```Python

...          source_transforms = [affine_trafo,                                         
                                         ])
            
            # XXXXXXXXXXXXXX
            # manual for now...            
            cview['sourceTransforms'].append(crop)
            
        
            mm.add_view_to_dataset(dataset_folder = datadir,                                       
                                   view_name = centname + "_crop",
                                   view = cview)
            ```

it accepts it.

**Comment by martinschorb** [comment]
But it looks like the crop is not done...

**Comment by martinschorb** [comment]
But that seems unrelated to the utils. Have to check the views.

**Comment by constantinpape** [comment]
> I have a validation error

I see, that's because of the `sources_after_transform`; I need to think about how to fix this.

But note that, I think, in your case that is not really necessary; the only case were source names after transform are really necessary if you want to show a single source several times in the same view; each time with a different trafo.

**Comment by constantinpape** [comment]
@martinschorb the issue should be fixed and https://github.com/mobie/mobie-utils-python/issues/27#issuecomment-886821479 should work; please try again

**Comment by constantinpape** [comment]
I think this all works now, so I am closing this; reopen if anything discussed here still does not work.
